#!/usr/bin/python3

import requests
import sys
import urllib3
import json



LOCALPATH="/usr/lib/zabbix/externalscripts/redfish/"

urllib3.disable_warnings(category=urllib3.exceptions.InsecureRequestWarning)

USER    = sys.argv[1]
PASS    = sys.argv[2]
HOST    = sys.argv[3]
URL     = sys.argv[4]

discovery = {'data': {}}

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
session = requests.Session()
session.auth = (USER, PASS)

auth = session.post('https://' + HOST, verify=False)
response = session.get('https://' + HOST + URL, verify=False).json()

discovery['data'] = response
print(json.dumps(discovery, indent=4))